name = "go-container-starter-gabi"
main = "src/index.js"
compatibility_date = "2025-03-10"

[observability]
enabled = true

[[containers]]
instances = 10
name = "go-hi-gabi"
class_name = "MyContainer"

[containers.configuration]
image = "."
network = { mode = "private" }

[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "MyContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer"]
